# -*- coding: utf-8 -*-
"""Kaggle Word Recognition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q24ashIKvQmdBmCv5rhWB7nMSaczxWgE
"""

!mkdir /root/.kaggle
import json
token = {"username":"you0824","key":"2e8ee96ce1abc9b4987d15cc7ce7be75"}
with open('/root/.kaggle/kaggle.json', 'w') as file:
    json.dump(token, file)
!chmod 600 /root/.kaggle/kaggle.json

!ls /root/.kaggle

!kaggle competitions download -c titanic

import pandas as pd

train = pd.read_csv("train.csv")
print(train.shape)

train.head()

!kaggle competitions download --force digit-recognizer

import seaborn as sns
sns.set(style='white', context='notebook', palette='deep')
train = pd.read_csv("train.csv")
y_train = train["label"].values
g = sns.countplot(y_train)

import matplotlib.pyplot as plt

X_train = train.drop("label", axis=1).values
y_train = train["label"].values
print(X_train.shape)

plt.imshow(X_train[7, :].reshape(28, 28), cmap='gray')
plt.xticks([])
plt.yticks([])
plt.show()

