# -*- coding: utf-8 -*-
"""YOLO image recognition model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19vf820RojujJJWJCNycZZ6yThdQ8gCVA

### 建立YOLO影像辨識模型
"""

! nvidia-smi

! git clone https://github.com/AlexeyAB/darknet

! cd darknet; head Makefile

! sed -i "1s/GPU=0/GPU=1/" darknet/Makefile
! sed -i "2s/CUDNN=0/CUDNN=1/" darknet/Makefile
! sed -i "4s/OPENCV=0/OPENCV=1/" darknet/Makefile

! cd darknet; head Makefile

! cd darknet; make

from PIL import Image
img = Image.open('/content/darknet/data/horses.jpg')
img

! wget https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights

! wget https://img-fnc.ebc.net.tw/EbcFnc/news/2018/06/03/1528018813_98225.jpg

! cd darknet; ./darknet detect /content/darknet/cfg/yolov4.cfg  /content/yolov4.weights /content/98225.jpg

Image.open('/content/darknet/predictions.jpg')

! wget https://cdn2.ettoday.net/images/3321/d3321214.jpg

! cd darknet; ./darknet detect /content/darknet/cfg/yolov4.cfg  /content/yolov4.weights /content/d3321214.jpg

Image.open('/content/darknet/predictions.jpg')

